# Generated by Django 3.1 on 2020-09-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedometerapp', '0004_auto_20200902_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steps',
            name='created_at',
            field=models.DateField(),
        ),
    ]
