# Generated by Django 3.1 on 2020-09-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedometerapp', '0005_auto_20200902_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steps',
            name='created_at',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='steps',
            name='steps',
            field=models.CharField(max_length=5),
        ),
    ]
