# Generated by Django 3.1 on 2020-09-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedometerapp', '0006_auto_20200904_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steps',
            name='created_at',
            field=models.DateField(max_length=10),
        ),
        migrations.AlterField(
            model_name='steps',
            name='steps',
            field=models.IntegerField(),
        ),
    ]
